services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    user: "1000:1000"
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - todo-network

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DYNAMODB_HOST=dynamodb-local
    depends_on:
      - dynamodb-local
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
